// Student review demo records and aggregated sentiment themes.
// Prototype/demo content — not live verified reviews.
import type { Review } from './mockData';

export type CollegeReview = Review & { collegeName: string; collegeId: string; collegeLogo: string };

export const INITIAL_REVIEWS: CollegeReview[] = [
  {
    id: 'rev-1',
    collegeId: 'coep',
    collegeName: 'College of Engineering Pune (COEP)',
    collegeLogo: '🏛️',
    studentType: 'Current Student',
    course: 'B.Tech Computer Engineering',
    batch: '2025',
    verified: true,
    overallRating: 4.6,
    facultyRating: 4.4,
    placementRating: 4.8,
    infrastructureRating: 4.2,
    hostelRating: 3.5,
    campusRating: 4.7,
    roiRating: 4.9,
    pros: [
      'Unbelievable ROI with fees under ₹1.5L/year and average CSE package ₹16.4L',
      'Extremely active technical clubs (MindSpark, CoEP Robotics)',
      'High industry prestige across Pune and Bangalore tech circles',
    ],
    cons: [
      'Hostel accommodation capacity is strictly limited for non-local students',
      'Bureaucratic administrative paperwork during scholarship submissions',
    ],
    experience:
      'COEP has a legacy that opens doors in tech giants. The coding culture is driven by student communities. Faculty in the computer department are research-focused and encourage patents. The Boat Club and heritage campus make student life genuinely memorable, even if hostel allotments are competitive.',
    helpfulCount: 142,
    reportCount: 0,
    date: '2026-03-12',
  },
  {
    id: 'rev-2',
    collegeId: 'iit-bombay',
    collegeName: 'IIT Bombay',
    collegeLogo: '🏛️',
    studentType: 'Verified Alumnus',
    course: 'B.Tech CSE',
    batch: '2023',
    verified: true,
    overallRating: 4.9,
    facultyRating: 4.8,
    placementRating: 5.0,
    infrastructureRating: 4.7,
    hostelRating: 4.0,
    campusRating: 4.9,
    roiRating: 5.0,
    pros: [
      'Unmatched global peer group and entrepreneurship ecosystem (E-Cell)',
      'Direct access to top global HFTs, Google Brain, and venture funds',
      '550-acre scenic campus nestled next to Powai Lake',
    ],
    cons: [
      'Relentless academic competition can be emotionally demanding',
      'Older hostel wings have smaller rooms compared to newly built blocks',
    ],
    experience:
      'IIT Bombay changes your mental horizon permanently. You are surrounded by Olympiad medalists and future founders. The placement season offers global roles with median packages of ₹28L. If you can handle the academic rigor, there is no better launching pad in Asia.',
    helpfulCount: 318,
    reportCount: 0,
    date: '2026-01-20',
  },
  {
    id: 'rev-3',
    collegeId: 'vjti',
    collegeName: 'Veermata Jijabai Technological Institute (VJTI)',
    collegeLogo: '⚙️',
    studentType: 'Current Student',
    course: 'B.Tech Information Technology',
    batch: '2026',
    verified: true,
    overallRating: 4.5,
    facultyRating: 4.2,
    placementRating: 4.7,
    infrastructureRating: 3.9,
    hostelRating: 3.2,
    campusRating: 4.0,
    roiRating: 4.9,
    pros: [
      'Strategic Mumbai location offers unbeatable internship access to fintech and IT headquarters',
      'Very affordable government fees with massive alumni support',
      'Strong placement consistency with 93% placed students',
    ],
    cons: [
      'Campus infrastructure is heritage and needs modernization in some labs',
      'Hostel mess menu is repetitive and facilities are average',
    ],
    experience:
      'VJTI is one of Maharashtra’s gems. The sheer location advantage in Matunga, Mumbai means tech firms interview on campus continuously. Professors in IT are very supportive for hackathons. The hostel is strict with entry times and mess food is decent but basic.',
    helpfulCount: 97,
    reportCount: 0,
    date: '2026-02-18',
  },
  {
    id: 'rev-4',
    collegeId: 'bits-pilani',
    collegeName: 'BITS Pilani',
    collegeLogo: '💡',
    studentType: 'Alumni',
    course: 'B.E. Computer Science',
    batch: '2024',
    verified: true,
    overallRating: 4.8,
    facultyRating: 4.7,
    placementRating: 4.8,
    infrastructureRating: 4.9,
    hostelRating: 4.5,
    campusRating: 4.8,
    roiRating: 4.3,
    pros: [
      'Zero attendance policy fosters self-driven projects and entrepreneurship',
      'Practice School (PS-1 & PS-2) guarantees 6-month industry internships',
      'Phenomenal BITSian alumni network worldwide',
    ],
    cons: [
      'Tuition fees have risen significantly in recent years (around ₹5.8L/year)',
      'Pilani remote location requires 4-hour cab/train travel to Delhi',
    ],
    experience:
      'The flexibility at BITS is unmatched. Zero attendance taught me discipline because grades still matter, but you have the freedom to build startups, join clubs, or prepare for research. Practice School 2 placed me directly at an American semiconductor firm.',
    helpfulCount: 204,
    reportCount: 0,
    date: '2025-11-04',
  },
  {
    id: 'rev-5',
    collegeId: 'manipal',
    collegeName: 'Manipal Academy of Higher Education',
    collegeLogo: '🌊',
    studentType: 'Current Student',
    course: 'B.Tech Data Science & Engineering',
    batch: '2025',
    verified: true,
    overallRating: 4.3,
    facultyRating: 4.1,
    placementRating: 4.2,
    infrastructureRating: 4.8,
    hostelRating: 4.7,
    campusRating: 4.9,
    roiRating: 3.8,
    pros: [
      'World-class university town vibe with state-of-the-art sports complex (MARENA)',
      'Modern labs with cloud computing and GPU clusters for AI research',
      'Diverse student body from across India and 40+ countries',
    ],
    cons: [
      'Higher fee structure compared to government institutions',
      'Need to stand out actively from large batch sizes during campus placements',
    ],
    experience:
      'Manipal offers arguably the best campus life in India. The library is open late, sports facilities are Olympic standard, and hostels are air-conditioned and well managed. CSE & Data Science placements are robust with 88% placed.',
    helpfulCount: 88,
    reportCount: 0,
    date: '2026-03-01',
  },
  {
    id: 'rev-6',
    collegeId: 'nmims',
    collegeName: 'NMIMS Mukesh Patel School of Technology (MPSTME)',
    collegeLogo: '🏢',
    studentType: 'Current Student',
    course: 'MBA Tech Computer Engineering',
    batch: '2025',
    verified: true,
    overallRating: 4.2,
    facultyRating: 4.3,
    placementRating: 4.1,
    infrastructureRating: 4.6,
    hostelRating: 3.6,
    campusRating: 4.1,
    roiRating: 3.7,
    pros: [
      'Integrated B.Tech + MBA Tech curriculum saves one full academic year',
      'Prime Juhu/Vile Parle Mumbai location with corporate guest lecturers weekly',
      'Strong corporate networking and Bloomberg terminal labs',
    ],
    cons: [
      'Hostel accommodation in Mumbai is expensive with limited institutional rooms',
      'Strict 80% attendance criteria strictly enforced with biometric tracking',
    ],
    experience:
      'If you want a corporate head-start blending technology with business management, NMIMS MPSTME is structured effectively. Case study methodologies are used throughout. The attendance policy is strict, so balance your schedule well.',
    helpfulCount: 65,
    reportCount: 0,
    date: '2026-02-11',
  },
];

export const THEMES_LIKE = [
  { name: 'Faculty & Mentorship', pct: 94, mentions: 1120, highlight: 'Accessible professors, research guidance, and industry-oriented teaching.' },
  { name: 'Campus Life & Culture', pct: 89, mentions: 980, highlight: 'Vibrant cultural & tech fests, student-led clubs, and collaborative peer groups.' },
  { name: 'Placement Support', pct: 91, mentions: 1040, highlight: 'Dedicated training & placement cells, mock interviews, and tier-1 recruiters.' },
  { name: 'Lab & Tech Infrastructure', pct: 86, mentions: 860, highlight: 'High-speed Wi-Fi, modern computer centers, and updated libraries.' },
];

export const THEMES_CONCERNS = [
  { name: 'Hostel Allotment & Facilities', pct: 41, mentions: 410, concern: 'Limited room availability for second-year students and older hostel washrooms.' },
  { name: 'Administrative Bureaucracy', pct: 34, mentions: 320, concern: 'Slow approval cycles for document verification, transcript requests, and scholarship paperwork.' },
  { name: 'Mess & Food Consistency', pct: 29, mentions: 290, concern: 'Repetitive food menus and limited culinary varieties across non-veg offerings.' },
  { name: 'Branch Placement Disparities', pct: 24, mentions: 210, concern: 'CSE and IT receive majority of ₹20L+ packages compared to Civil and Metallurgy.' },
];
